from pydantic import BaseModel, Field

from imessage_data_foundry.personas.models import (
    CommunicationFrequency,
    EmojiUsage,
    ResponseTime,
    VocabularyLevel,
)


class PersonaConstraints(BaseModel):
    """Constraints for persona generation."""

    relationship: str | None = Field(default=None, description="e.g., friend, family, coworker")
    communication_frequency: CommunicationFrequency | None = None
    typical_response_time: ResponseTime | None = None
    emoji_usage: EmojiUsage | None = None
    vocabulary_level: VocabularyLevel | None = None
    age_range: tuple[int, int] | None = Field(default=None, description="Min and max age")
    topics: list[str] | None = Field(default=None, description="Topics they discuss")
    personality_traits: list[str] | None = Field(default=None, description="Key traits")


class GeneratedMessage(BaseModel):
    """A message generated by the LLM before timestamp assignment."""

    text: str
    sender_id: str = Field(description="Persona ID of the sender")
    is_from_me: bool = Field(description="True if sender is the 'self' persona")


class GeneratedPersona(BaseModel):
    """Raw persona data generated by LLM before full model creation."""

    name: str
    personality: str
    writing_style: str
    relationship: str
    communication_frequency: str = "medium"
    typical_response_time: str = "minutes"
    emoji_usage: str = "light"
    vocabulary_level: str = "moderate"
    topics_of_interest: list[str] = Field(default_factory=list)
